rm(list = ls())

# Libraries ---------------------------------------------------------------
library(shinythemes)
library(visNetwork)
library(rpart)
library(shiny)
library(geomnet)
library(igraph)
library(rsconnect)
library(plyr)
library(dplyr)
library(tidyr)
library(shinydashboard)
library("XML")
library("methods")
library(xml2)
library(hash)
library(DT)
  